export const glossary = [
  ['Annual Notice of Change (ANOC)', 'A notice Medicare Advantage and Part D plans send each fall describing changes to the plan for the coming year.'],
  ['Coinsurance', 'The percentage of a covered service’s cost that you pay after any deductible, such as 20%.'],
  ['Copayment (copay)', 'A fixed amount you pay for a covered service or prescription, such as a set amount for a doctor visit.'],
  ['Creditable coverage', 'Other health or drug coverage that meets Medicare’s standards, which can let you delay enrolling without a late enrollment penalty. Your plan tells you in writing whether its coverage is creditable.'],
  ['Deductible', 'The amount you pay for covered services before your coverage starts to pay.'],
  ['Evidence of Coverage (EOC)', 'The plan document that explains in detail what a plan covers, what you pay, and your rights.'],
  ['Formulary', 'A plan’s list of covered prescription drugs.'],
  ['HMO (Health Maintenance Organization)', 'A type of Medicare Advantage plan that generally requires you to use doctors and hospitals in its network, except in emergencies, and may require referrals to see specialists.'],
  ['Maximum out-of-pocket limit', 'In Medicare Advantage, the most you pay in a year for covered Part A and Part B services. Original Medicare does not have this kind of yearly limit.'],
  ['Medicare Advantage (Part C)', 'A Medicare-approved plan from a private company that provides your Part A and Part B coverage, often with drug coverage included.'],
  ['Medicare Supplement Insurance (Medigap)', 'A policy from a private company that helps pay some costs Original Medicare does not cover. It works only with Original Medicare.'],
  ['Network', 'The doctors, hospitals, pharmacies, and other providers a plan contracts with.'],
  ['Original Medicare', 'Part A and Part B, managed by the federal government. You can see any doctor or hospital in the U.S. that accepts Medicare.'],
  ['Part D', 'Medicare prescription drug coverage, offered by Medicare-approved private companies.'],
  ['PPO (Preferred Provider Organization)', 'A type of Medicare Advantage plan with a network that also lets you use out-of-network providers, usually at a higher cost.'],
  ['Premium', 'The amount you pay, usually monthly, to have coverage.'],
  ['Scope of Appointment (SOA)', 'A record, required before a personal meeting to discuss specific Medicare plans, of which types of coverage you agreed to discuss.'],
]
